apiVersion: arm.azure.com/v1
kind: AzureResourceSecret
metadata:
  name: test
spec:
  resource:
    ref:
      name: test
  target:
    name: test
  apiVersion: 2021-01-01
  endpoint:
    method: post
    path: listKeys
    query:
      $expand: kerb
  template:
    stringData:
      key0: "{{ keys.0.value }}"
      key1: "{{ keys.1.value }}"
