apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azuresubscriptions.arm.azure.com
spec:
  group: arm.azure.com
  names:
    kind: AzureSubscription
    listKind: AzureSubscriptionList
    plural: azuresubscriptions
    singular: azuresubscription
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              id:
                description: ID of the subscription.
                type: string
              subscriptionId:
                description: Unique ID of the subscription.
                type: string
              tenantId:
                description: Tenant ID of the subscription.
                type: string
              name:
                description: Name of the subscription.
                type: string
              tags:
                description: Tags of the subscription.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              state:
                description: State of the subscription.
                type: string
              error:
                description: Last error manipulating the subscription.
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              name:
                description: Name of the Azure subscription.
                type: string
            required:
            - name
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
