apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureresourceconfigmaps.arm.azure.com
spec:
  group: arm.azure.com
  names:
    kind: AzureResourceConfigMap
    listKind: AzureResourceConfigMapList
    plural: azureresourceconfigmaps
    singular: azureresourceconfigmap
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              resourceId:
                description: ID of the resource being listed.
                type: string
              configMapNamespace:
                description: Namespace of the resulting configmap.
                type: string
              configMapName:
                description: Name of the resulting configmap.
                type: string
              refreshTime:
                description: The time and date the resource value was fetched and the target config map was updated.
                format: date-time
                nullable: true
                type: string
              state:
                description: Current state of the reconcilation.
                type: string
              error:
                description: Last error that occurred attempting to reconcile.
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              resource:
                description: Reference to the Azure resource to invoke the operation on.
                properties:
                  query:
                    description: If specified, an existing Azure resource will be located.
                    properties:
                      resourceGroup:
                        description: Method of locating the resource group for the resource.
                        properties:
                          query:
                            description: If specified, an existing Azure resource group will be located.
                            properties:
                              subscription:
                                description: ID of the Azure subscription to locate.
                                properties:
                                  query:
                                    description: If specified, an existing Azure subscription will be located.
                                    properties:
                                      id:
                                        description: ID of the subscription to locate.
                                        type: string
                                      name:
                                        description: Name of the subscription to locate.
                                        type: string
                                    type: object
                                  ref:
                                    description: If specified, the Azure subscription will be provided by the located AzureSubscription resource.
                                    properties:
                                      namespace:
                                        description: Optional Kubernetes namespace of the AzureSubscription resource.
                                        type: string
                                      name:
                                        description: Name of the Kubernetes AzureSubscription resource.
                                        type: string
                                    required:
                                    - name
                                    type: object
                                type: object
                              name:
                                description: Name of the Azure resource group within the specified subscription.
                                type: string
                            required:
                            - subscription
                            - name
                            type: object
                          ref:
                            description: If specified, the Azure resource group will be provided by the located AzureResourceGroup resource.
                            properties:
                              namespace:
                                description: Optional Kubernetes namespace of the AzureResourceGroup resource.
                                type: string
                              name:
                                description: Name of the AzureResourceGroup resource.
                                type: string
                            required:
                            - name
                            type: object
                        type: object
                      parentResource:
                        description: Parent resource. Typed as a AzureResourceLink.
                        properties: {}
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      resourceProvider:
                        description: Name of the resource provider of the resource.
                        type: string
                      resourceType:
                        description: Type of the resource.
                        type: string
                      name:
                        description: Name of the Azure resource.
                        type: string
                    required:
                    - resourceProvider
                    - resourceType
                    - name
                    type: object
                  ref:
                    description: If specified, the Azure resource will be provided by the located AzureResource resource.
                    properties:
                      namespace:
                        description: Optional Kubernetes namespace of the AzureResource resource.
                        type: string
                      name:
                        description: Name of the AzureResource resource.
                        type: string
                    required:
                    - name
                    type: object
                type: object
              apiVersion:
                description: API version of the operation.
                type: string
              endpoint:
                description: Optionally, retrieve the configmap data from a nested endpoint of the resource. This can be used to invoke the List* family of operations.
                properties:
                  method:
                    description: HTTP method to use against the endpoint.
                    type: string
                  path:
                    description: Name of the operation endpoint. An example might be "listKeys".
                    type: string
                  body:
                    description: Body of the request to send to the endpoint.
                    properties: {}
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  query:
                    description: Query strings to add to the request to the endpoint.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - method
                - path
                type: object
              refreshInterval:
                description: The amount of time between reading the values from the resource.
                type: string
              target:
                description: Specification of the target configmap.
                properties:
                  namespace:
                    description: Namespace of the config map.
                    type: string
                  name:
                    description: Name of the config map.
                    type: string
                required:
                - name
                type: object
              template:
                description: Description of the configmap to generate.
                properties:
                  metadata:
                    description: Gets the metadata of the resulting configmap.
                    properties:
                      annotations:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      labels:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  binaryData:
                    description: Gets the data of the resulting configmap.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  data:
                    description: Gets the data of the resulting configmap.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
            required:
            - resource
            - apiVersion
            - target
            - template
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
